configure_dotfiles: true  
configure_sudoers: true
configure_terminal: false
configure_osx: true

yd_host_user_name: ""
yd_host_name_prefix: ""
yd_jenkins_agent_user: ""
yd_jenkins_agent_password: ""

yd_shell: "/bin/bash"

dotfiles_repo: ""
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .profile
  - .bash_profile
  - configure_osx.sh
  - Development.p12
  - Distribution.p12

homebrew_upgrade_all_packages: true
homebrew_installed_packages:
  - "python@3.7"
  - "jq"
  - "chargepoint/xcparse/xcparse" 
  - "coreutils"
  - "xmlstarlet"
  - "libffi"
  - "ruby-build"
  - "openjdk"

homebrew_uninstalled_packages:
  - "adoptopenjdk8"

homebrew_sudo_password: ""
homebrew_cask_appdir: /Applications
homebrew_cask_apps: []
  # - adoptopenjdk/openjdk/adoptopenjdk8

mas_upgrade_all_apps: fasle
mas_email: ""
mas_password: ""
mas_installed_apps: []

osx_script: "~/configure_osx.sh --no-restart"

# TODO
# Automate gems installation issue in the tasks/install_xcode.yml
# cd $(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0 && ln -s universal-darwin20 universal-darwin19
#
# https://github.com/CocoaPods/CocoaPods/issues/10286#issuecomment-750403566
#
gem_packages_become: true
gem_packages:
  - name: cocoapods
    version: "1.10.1"
  - name: cocoapods-binary
    version: "0.4.4"
  - name: xcodeproj
    version: "1.19.0"
  - name: nokogiri
    version: "1.10.10"
  - name: fastlane
    version: "2.157.2"
    state: "absent"
  - name: fastlane
    version: "2.157.3"
    state: "absent"
  - name: fastlane
    version: "2.167.0"
    state: "absent"
  - name: fastlane
    version: "2.168.0"
    state: "absent"
  - name: fastlane
    version: "2.175.0"
  - name: fastlane-plugin-firebase_app_distribution
    version: "0.2.0"
    state: "absent"
  - name: fastlane-plugin-firebase_app_distribution
    version: "0.2.4"
    state: "absent"
  - name: fastlane-plugin-firebase_app_distribution
    version: "0.2.5"

pip_executable: "pip3.7"
pip_packages:
  - name: youtrack
    version: "0.1.69"
    executable: "{{ pip_executable }}"
  - name: python-gitlab
    version: "2.6.0"
    executable: "{{ pip_executable }}"
  - name: python-jenkins
    version: "1.7.0"
    executable: "{{ pip_executable }}"
  - name: slackclient
    version: "2.9.3"
    executable: "{{ pip_executable }}"
  - name: configparser 
    version: "5.0.0"
    executable: "{{ pip_executable }}"

yd_osx_updates_for_install:
  - "macOS Catalina 10.15.6 Update- "
  - "macOS Catalina 10.15.6 Supplemental Update- "
  - "Safari14.0CatalinaAuto-14.0"
  - "macOS Catalina 10.15.7 Update- "
  - "macOS Catalina 10.15.7 Supplemental Update- "
  - "Command Line Tools for Xcode-12.1"
  # - "Command Line Tools beta 5 for Xcode-12.0"
  - "Command Line Tools for Xcode-12.2"
  - "Safari14.0.1CatalinaAuto-14.0.1"
  - "Safari14.0.2CatalinaAuto-14.0.2"
  - "macOS Big Sur 11.1 Update-20C69"
  - "Обновление macOS Big Sur 11.1-20C69"
  - "Security Update 2020-001-10.15.7"
  - "macOS Big Sur-20D74"
  - "macOS Big Sur-20D74"
  - "macOS Catalina 10.15.7 Supplemental Update-10.15.7"
  - "Safari14.0.3CatalinaAuto-14.0.3"
  - "macOS Big Sur 11.2.2-20D80"
  - "macOS Big Sur 11.2.2-20D80"
  - "macOS Big Sur 11.2.3-20D91"
  - "macOS Big Sur 11.2.3-20D91"
  - "Safari14.0.3CatalinaAuto-14.0.3"

yd_share_network_resource: ""
yd_share_mount_point: ""
yd_required_xcode_version: "12.4"
yd_xcode_file_name: "Xcode_{{yd_required_xcode_version}}.xip"

yd_swarm_client_version: "3.23"

yd_required_identities: []

yd_identities_keychain: ""
yd_jenkins_hostname: ""
yd_jenkins_ip: ""

yd_adp_email: ""

pre_provision_tasks: 
  - "{{ playbook_dir }}/tasks/ssh-keys.yml"
  - "{{ playbook_dir }}/tasks/osx-updates.yml"
  - "{{ playbook_dir }}/tasks/install_xcode.yml"
  - "{{ playbook_dir }}/tasks/prepare_askpass.yml"
 
# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: 
  - "{{ playbook_dir }}/tasks/crontab.yml"
  - "{{ playbook_dir }}/tasks/jenkins.yml"
  - "{{ playbook_dir }}/tasks/identities.yml"
  - "{{ playbook_dir }}/tasks/git.yml"
  - "{{ playbook_dir }}/tasks/spaceauth.yml"
  - "{{ playbook_dir }}/tasks/remove_askpass.yml"
