configure_dotfiles: yes  
configure_sudoers: yes
configure_terminal: no
configure_osx: yes

yd_host_user_name: ""
yd_host_name_prefix: ""
yd_jenkins_agent_user: ""
yd_jenkins_agent_password: ""

dotfiles_repo: ""
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .profile
  - .bash_profile
  - configure_osx.sh
  - Development.p12
  - Distribution.p12

homebrew_upgrade_all_packages: yes
homebrew_installed_packages:
  - "python@3.7"
  - "jq"
  - "chargepoint/xcparse/xcparse" 
  - "coreutils"

homebrew_uninstalled_packages: 
  - "openjdk"

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - sublime-text
  - adoptopenjdk/openjdk/adoptopenjdk8

mas_upgrade_all_apps: no
mas_email: ""
mas_password: ""
mas_installed_apps: []

osx_script: "~/configure_osx.sh --no-restart"

gem_packages_become: yes
gem_packages:
  - name: cocoapods
    version: "1.9.3"
  - name: cocoapods-binary
    version: "0.4.4"
  - name: xcodeproj
    version: "1.18.0"
  - name: nokogiri
    version: "1.10.10"
  - name: fastlane
    version: "2.157.2"
    state: "absent"
  - name: fastlane
    version: "2.157.3"
  - name: fastlane-plugin-firebase_app_distribution
    version: "0.2.0"

pip_executable: "pip3.7"
pip_packages:
  - name: youtrack
    version: "0.1.69"
    executable: "{{ pip_executable }}"
  - name: python-gitlab
    version: "1.8.0"
    executable: "{{ pip_executable }}"
  - name: python-jenkins
    version: "1.7.0"
    executable: "{{ pip_executable }}"
  - name: slackclient
    version: "1.3.0"
    executable: "{{ pip_executable }}"
  - name: configparser 
    version: "5.0.0"
    executable: "{{ pip_executable }}"

yd_osx_updates_for_install:
  - "macOS Catalina 10.15.6 Update- "
  - "macOS Catalina 10.15.6 Supplemental Update- "
  # - "Command Line Tools beta 5 for Xcode-12.0"

yd_share_network_resource: ""
yd_share_mount_point: ""
yd_required_xcode_version: "11.7"
yd_xcode_file_name: "Xcode_{{yd_required_xcode_version}}.xip"

yd_swarm_client_version: "3.23"

yd_required_identities: []

yd_identities_keychain: ""
yd_jenkins_hostname: ""
yd_jenkins_ip: ""

pre_provision_tasks: 
  - "{{ playbook_dir }}/tasks/ssh-keys.yml"
  - "{{ playbook_dir }}/tasks/osx-updates.yml"
  - "{{ playbook_dir }}/tasks/install_xcode.yml"
 
# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: 
  - "{{ playbook_dir }}/tasks/crontab.yml"
  - "{{ playbook_dir }}/tasks/jenkins.yml"
  - "{{ playbook_dir }}/tasks/identities.yml"
  - "{{ playbook_dir }}/tasks/git.yml"
