configure_dotfiles: yes  
configure_sudoers: yes
configure_terminal: no
configure_osx: yes

dotfiles_repo: ""
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .profile
  - .bash_profile
  - configure_osx.sh

homebrew_installed_packages:
  - "python@3.7"
  - "jq"
  - "xcparse" 
  - "coreutils"

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - sublime-text

mas_upgrade_all_apps: no
mas_email: ""
mas_password: ""
mas_installed_apps: 
  - name: "Xcode"
    id: 497799835

osx_script: "~/configure_osx.sh --no-restart"

gem_packages_become: yes
gem_packages:
  - name: cocoapods
    version: "1.9.3"
  - name: cocoapods-binary
    version: "0.4.4"
  - name: xcodeproj
    version: "1.16.0"
  - name: nokogiri
    version: "1.10.9"
  - name: fastlane
    version: "2.150.1"

pip_executable: "pip3.7"
pip_packages:
  - name: youtrack
    version: "0.1.69"
    executable: "{{ pip_executable }}"
  - name: python-gitlab
    version: "1.8.0"
    executable: "{{ pip_executable }}"
  - name: python-jenkins
    version: "1.7.0"
    executable: "{{ pip_executable }}"
  - name: slackclient
    version: "1.3.0"
    executable: "{{ pip_executable }}"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: 
  - "{{ playbook_dir }}/tasks/crontab.yml"
