---
# TODO: Use sudo once .osx can be run via root with no user interaction.
- name: Run .osx dotfiles.
  command: "{{ osx_script }}"
  changed_when: false

- name: Check .bashrc Type
  stat:
    path: ~/.bashrc
  register: bashrc_type

- name: Link .bashrc
  file:
    path: ~/.bashrc
    state: absent
  when: bashrc_type.stat.exists and not bashrc_type.stat.islnk

- name: Link .bashrc to .bash_profile
  file:
    src: ~/.bash_profile
    dest: ~/.bashrc
    state: link

- name: Get current SHELL
  command: echo $SHELL
  register: current_shell
  changed_when: false

- name: Ensure required SHELL
  command: chsh -s {{ yd_shell }} {{ yd_host_user_name }}
  become: true
  when: current_shell.stdout != yd_shell

